/* Assemble staging (ชุดเดิม) + staging2 (ชุดใหม่) → assets/data.js
   Emits: const SETS = [...]; const BOOKS = [...] กันเว็บแยกชุดได้ */
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const OLD = path.join(ROOT, 'staging');
const NEW = path.join(ROOT, 'staging2');
const OUT = path.join(ROOT, 'assets', 'data.js');

const SETS = [
  { id: 'ชุดเดิม', name: 'ชุดเดิม · บท 11–17', icon: '📚',
    desc: 'เภสัชวิทยา/พยาบาลศาสตร์ ชุดแรก (บทที่ 11–17) + ส่วนเสริมสไลด์' },
  { id: 'ประเมิน', name: 'ชุดใหม่ · การประเมินภาวะสุขภาพ', icon: '🩺',
    desc: 'การประเมินภาวะสุขภาพแบบองค์รวม + ตรวจร่างกายรายระบบ (5 บท)' },
  { id: 'แนวคิด', name: 'ชุดใหม่ · แนวคิดและหลักการพยาบาล', icon: '💡',
    desc: 'ทักษะพื้นฐานการพยาบาล การทำแผล ทางเดินหายใจ การรับใหม่–จำหน่าย–ส่งต่อ ฯลฯ (15 บท)' },
];

function load(dir, name) {
  const p = path.join(dir, name + '.json');
  if (!fs.existsSync(p)) throw new Error('missing ' + p);
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function validate(b, tag) {
  const errs = [];
  if (!b.id || (!b.no && b.no !== 0) || !b.title) errs.push('missing id/no/title');
  if (!b.summary || b.summary.length < 300) errs.push('summary too short: ' + (b.summary || '').length);
  if (!Array.isArray(b.questions) || b.questions.length < 8) errs.push('questions < 8');
  (b.questions || []).forEach((q, i) => {
    if (!q.q) errs.push(`q${i} no text`);
    if (!Array.isArray(q.choices) || q.choices.length !== 4) errs.push(`q${i} choices!=4`);
    if (typeof q.answer !== 'number' || q.answer < 0 || q.answer > 3) errs.push(`q${i} bad answer`);
    if (!q.explain) errs.push(`q${i} no explain`);
  });
  if (errs.length) throw new Error(`[${tag}] ` + errs.join('; '));
}

const books = [];

/* ---------- ชุดเดิม: บท 11–17 (+ ส่วนเสริม *_v) ---------- */
const OLD_ORDER = ['ch11', 'ch12', 'ch13', 'ch14', 'ch15', 'ch16', 'ch17'];
for (const id of OLD_ORDER) {
  let b;
  try { b = load(OLD, id); } catch (e) { console.log('SKIP ' + id + ': ' + e.message); continue; }
  try {
    const v = load(OLD, id + '_v');
    b.summary = (b.summary || '') + '\n\n' + (v.summary || '');
    b.questions = (b.questions || []).concat(v.questions || []);
    if (v.source && !(b.source || '').includes(v.source)) b.source = (b.source || '') + ' + ' + v.source;
    console.log(`  merged ${id}_v: +${v.questions.length} Q`);
  } catch (e) { /* no extra */ }
  b.set = 'ชุดเดิม';
  validate(b, id);
  books.push(b);
}

/* ---------- ชุดใหม่: staging2 (a1-a5, b1-b15) เรียงตาม set + เลขบท ---------- */
const NEW_ORDER = ['a1', 'a2', 'a3', 'a4', 'a5',
  'b1', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'b10', 'b2',
  'b11', 'b12', 'b13', 'b15', 'b14'];
for (const id of NEW_ORDER) {
  let b;
  try { b = load(NEW, id); } catch (e) { console.log('SKIP ' + id + ': ' + e.message); continue; }
  if (!b.set) b.set = 'แนวคิด';
  validate(b, id);
  books.push(b);
}

/* ---------- เรียงลำดับ + ตรวจความครบ ---------- */
const setIndex = id => { const i = SETS.findIndex(s => s.id === id); return i < 0 ? 99 : i; };
books.sort((a, b) => {
  const sa = setIndex(a.set), sb = setIndex(b.set);
  if (sa !== sb) return sa - sb;
  const na = parseFloat(a.no) || 0, nb = parseFloat(b.no) || 0;
  if (na !== nb) return na - nb;
  return String(a.id).localeCompare(String(b.id));
});

const total = books.reduce((n, b) => n + b.questions.length, 0);
const header =
`/* auto-generated by build_all.js — ข้อสอบแฟน (2 ชุด) */
const SETS = ${JSON.stringify(SETS, null, 1)};
const BOOKS = `;
fs.writeFileSync(OUT, header + JSON.stringify(books, null, 1) + ';\n');

console.log('\nWROTE', OUT);
for (const s of SETS) {
  const bs = books.filter(b => b.set === s.id);
  if (!bs.length) continue;
  console.log(`\n[${s.id}] ${bs.length} บท  ${bs.reduce((n, b) => n + b.questions.length, 0)} ข้อ`);
  bs.forEach(b => console.log(`   ${String(b.no).padStart(5)} ${b.icon || '📄'} ${b.title} (${b.questions.length}Q)`));
}
console.log('\nTOTAL:', books.length, 'บท /', total, 'ข้อ');
